# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # Providers: production uses Twilio, dev uses fakes (see when@dev below)
    App\Provider\SMS\SmsProvider:
        alias: App\Provider\SMS\TwilioSmsProvider

    App\Provider\Call\CallProvider:
        alias: App\Provider\Call\TwilioCallProvider

when@dev:
    services:
        App\Provider\SMS\SmsProvider:
            alias: App\Provider\SMS\FakeSmsProvider

        App\Provider\Call\CallProvider:
            alias: App\Provider\Call\FakeCallProvider

when@test:
    services:
        _defaults:
            public: true

        App\Provider\SMS\SmsProvider:
            alias: App\Provider\SMS\FakeSmsProvider

        App\Provider\Call\CallProvider:
            alias: App\Provider\Call\FakeCallProvider
